#!/bin/bash

#Detect root vs non root, assign PS1 and PS2
if [ "`id -u`" -eq 0 ]; then
  PS1="\[\033[0m\]\t \u@\h \W \[\033[0;31m\]\\$\[\033[1;37m\] > \[\033[0m\]"
  PS2="\[\033[1;37m\] > \[\033[\e[0m\]"
else
  PS1="\[\033[0m\]\t \u@\h \W \[\033[0;32m\]\\$\[\033[1;37m\] > \[\033[0m\]"
  PS2="\[\033[1;37m\] > \[\033[\e[0m\]"
fi
