alias ll='ls -la'
alias yolo='git commit -m "DO IT LIVE" .'
alias ppjson='python -m json.tool'

# git aliases
alias gc='git commit'
alias gp='git push'
alias ga='git add'
alias gs='git status'
alias gl='git pull'
