#!/bin/bash

# This file can go in ~/.bash/bash_prompt, or be placed in /etc/profile.d/bash_prompt.sh to work globally.

# This shortens the current path.
OSFAM=$(uname -s)
if [ $OSFAM = "Darwin" ] ; then
  PROMPT_COMMAND='CurDir=`pwd|sed -e "s!$HOME!~!"|sed -E "s!([^/])[^/]+/!\1/!g"`'
elif [ $OSFMA = "Linux" ] ; then
  PROMPT_COMMAND='CurDir=`pwd|sed -e "s!$HOME!~!"|sed -re "s!([^/])[^/]+/!\1/!g"`'
fi

#Detect root vs non root, assign PS1 and PS2
if [ "`id -u`" -eq 0 ] ; then
  PS1="\[\033[0m\]\t \u@\h \$CurDir \[\033[0;31m\]\\$\[\033[1;37m\] > \[\033[0m\]"
  PS2="\[\033[1;37m\] > \[\033[\e[0m\]"
else
  PS1="\[\033[0m\]\t \u@\h \$CurDir \[\033[0;32m\]\\$\[\033[1;37m\] > \[\033[0m\]"
  PS2="\[\033[1;37m\] > \[\033[\e[0m\]"
fi
