# general aliases
alias ll='ls -la'
alias yolo='git commit -m "DO IT LIVE" .'
alias ppjson='python -m json.tool'
alias randompass16='date +%s | md5sum | base64 | head -c 16 ; echo'
alias randompass32='date +%s | md5sum | base64 | head -c 32 ; echo'

# git aliases
alias gc='git commit'
alias gcm='git commit -m'
alias gp='git push'
alias ga='git add'
alias gs='git status'
alias gl='git pull'
alias gco='git checkout'
